# Generated by Django 2.2.2 on 2019-06-28 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('link_direct_name', models.CharField(max_length=100, null=True, unique=True)),
                ('link_reverse_name', models.CharField(max_length=100, null=True, unique=True)),
                ('speed', models.CharField(max_length=20, verbose_name='Speed (m/s)')),
                ('height', models.CharField(max_length=20, verbose_name='Height (m)')),
                ('living', models.BooleanField(default=False)),
                ('implies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consequences', to='myknowapp.Concept')),
                ('is_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='myknowapp.Concept')),
                ('is_composed_of', models.ManyToManyField(null=True, related_name='components', to='myknowapp.Concept')),
                ('is_linked_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked', to='myknowapp.Concept')),
            ],
            options={
                'db_table': 'concept',
                'managed': True,
            },
        ),
    ]
