# Generated by Django 2.2.2 on 2019-06-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='is_composed_of',
            field=models.ManyToManyField(related_name='components', to='myknowapp.Concept'),
        ),
    ]
