# Generated by Django 2.2.2 on 2019-06-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0002_auto_20190628_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='height',
            field=models.CharField(max_length=20, null=True, verbose_name='Height (m)'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='speed',
            field=models.CharField(max_length=20, null=True, verbose_name='Speed (m/s)'),
        ),
    ]
