# Generated by Django 2.2.2 on 2019-06-28 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0003_auto_20190628_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='is_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='myknowapp.Concept'),
        ),
    ]
