# Generated by Django 2.2.2 on 2019-06-28 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0004_auto_20190628_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Height (m)'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='implies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consequences', to='myknowapp.Concept'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='is_composed_of',
            field=models.ManyToManyField(blank=True, related_name='components', to='myknowapp.Concept'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='is_linked_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked', to='myknowapp.Concept'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='link_direct_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='link_reverse_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='speed',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Speed (m/s)'),
        ),
    ]
