# Generated by Django 2.2.2 on 2019-07-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0005_auto_20190628_2209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Concept',
            new_name='Entity',
        ),
        migrations.AlterModelTable(
            name='entity',
            table='entity',
        ),
    ]
