# Generated by Django 2.2.2 on 2019-07-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0006_auto_20190701_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'managed': True, 'verbose_name_plural': 'Entities'},
        ),
    ]
