# Generated by Django 2.2.2 on 2019-07-02 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0008_auto_20190701_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.AddField(
            model_name='entity',
            name='date_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='date_death',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='opposite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myknowapp.Entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_entity_related_+', to='myknowapp.Entity'),
        ),
    ]
