# Generated by Django 2.2.2 on 2019-07-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0009_auto_20190702_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='perso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='date_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
