# Generated by Django 2.2.2 on 2019-07-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0011_auto_20190702_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='is_linked_to',
            new_name='linked_to',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='related',
        ),
        migrations.AddField(
            model_name='entity',
            name='related_to',
            field=models.ManyToManyField(blank=True, help_text="WEAK link (like 'is friend of', 'is synonym of', ...)", related_name='_entity_related_to_+', to='myknowapp.Entity'),
        ),
    ]
