# Generated by Django 2.2.2 on 2019-07-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0012_auto_20190702_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='link_direct_name',
            new_name='linked_to_direct_name',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='link_reverse_name',
            new_name='linked_to_reverse_name',
        ),
    ]
