# Generated by Django 2.2.2 on 2019-07-03 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0013_auto_20190702_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='components',
        ),
        migrations.AddField(
            model_name='entity',
            name='implies_not',
            field=models.BooleanField(default=False, help_text='implies NOT'),
        ),
        migrations.CreateModel(
            name='EntityHasComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='myknowapp.Entity')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='myknowapp.Entity')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='entityhascomponents',
            field=models.ManyToManyField(blank=True, related_name='iscomponentof', through='myknowapp.EntityHasComponent', to='myknowapp.Entity'),
        ),
    ]
