# Generated by Django 2.2.2 on 2019-07-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0014_auto_20190703_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='entityhascomponents',
            new_name='has_components',
        ),
    ]
