# Generated by Django 2.2.2 on 2019-07-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0016_auto_20190703_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='abbr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
