# Generated by Django 2.2.2 on 2019-07-03 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0017_entity_abbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityhascomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='myknowapp.Entity'),
        ),
        migrations.AlterField(
            model_name='entityhascomponent',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='myknowapp.Entity'),
        ),
    ]
