# Generated by Django 2.2.2 on 2019-07-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0018_auto_20190703_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='not_me',
            field=models.BooleanField(default=False, help_text='NOT me'),
        ),
    ]
