# Generated by Django 2.2.2 on 2019-07-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0019_entity_not_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='related_to',
        ),
        migrations.AddField(
            model_name='entity',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='_entity_synonyms_+', to='myknowapp.Entity'),
        ),
    ]
