# Generated by Django 2.2.2 on 2019-07-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0020_auto_20190704_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_entities', to='myknowapp.Entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_domain',
            field=models.BooleanField(default=False),
        ),
    ]
