# Generated by Django 2.2.2 on 2019-07-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0021_auto_20190704_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
