# Generated by Django 2.2.2 on 2019-07-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0022_entity_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'managed': True, 'verbose_name_plural': 'entities'},
        ),
    ]
