# Generated by Django 2.2.2 on 2019-07-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0023_auto_20190705_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='perimeter',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Perimeter (km)'),
        ),
        migrations.AddField(
            model_name='entity',
            name='radius',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Radius (km)'),
        ),
        migrations.AddField(
            model_name='entity',
            name='speed_rotation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Speed (km/h)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='speed',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Speed (km/s)'),
        ),
    ]
