# Generated by Django 2.2.2 on 2019-07-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0025_auto_20190705_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='linked_to_direct_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='linked_to_reverse_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
