# Generated by Django 2.2.2 on 2019-07-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0026_auto_20190708_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='radius',
            new_name='a_radius',
        ),
    ]
