# Generated by Django 2.2.2 on 2019-07-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myknowapp', '0028_auto_20190708_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='depth',
            new_name='a_depth',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='frequency',
            new_name='a_frequency',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='height',
            new_name='a_height',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='length',
            new_name='a_length',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='wavelength',
            new_name='a_wavelength',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='width',
            new_name='a_width',
        ),
    ]
